---
- hosts: '{{ target | default("localhost") }}'
  become: yes 
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
  - name: Create conf dir
    file:
      path: "{{ item }}"
      state: directory
      recurse: yes
      mode: 0775
    with_items:
      - "conf/httpd_conf"
      - "conf/nginx"
      - "conf/nginx/conf.d"
      - "conf/redis"
      - "conf/supervisord"

  # apache conf
  - name: Copy apache vhost local
    template:
      src: apache.local.conf.j2
      dest: conf/httpd_conf/{{ fqdn_local }}.conf
      mode: 0664

  - name: Copy apache vhost live
    template:
      src: apache.live.conf.j2
      dest: conf/httpd_conf/{{ fqdn_live }}.conf
      mode: 0664
     
  - name: Copy apache vhost staging
    template:
      src: apache.staging.conf.j2
      dest: conf/httpd_conf/{{ fqdn_staging }}.conf
      mode: 0664

  # supervisord  conf
  - name: Copy supervisord
    template:
      src: supervisord.j2
      dest: conf/supervisord/supervisord.conf
      mode: 0664

  # nginx local conf
  - name: Copy nginx conf file
    template:
      src: nginx.conf.j2
      dest: conf/nginx/nginx.conf
      mode: 0664

  - name: Copy nginx vhost
    template:
      src: nginx.vhost.conf.j2
      dest: conf/nginx/conf.d/{{ fqdn_local }}.conf
      mode: 0664